apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-dev-secret-syst-2374-sonarqube-saml
  namespace: ns-nb-clone-sonarqube
spec:
  vaultAuthRef: "vault-secrets-operator/vault-dev-kubernetes-syst-2374-sonarqube-auth"
  namespace: "sandbox-alpana"
  refreshAfter: "30s"
  hmacSecretData: true
  type: "kv-v2"
  mount: "syst-2374"
  path: "brm/infrastructure/shared/sonarqube"
  syncConfig:
    instantUpdates: false
  rolloutRestartTargets:
    - kind: StatefulSet
      name: "nb-clone-sonarqube"
  destination:
    name: "nb-clone-sonarqube-properties"
    create: true
    overwrite: true
    type: "Opaque"
    transformation:
      excludeRaw: true
      excludes:
        - ".*"
      templates:
        "secret.properties":
          text: |
            sonar.auth.saml.certificate.secured={{ get .Secrets "sonarqube_clone_saml_provider_certificate" | replace "\n" "\\\n" }}
            sonar.auth.saml.applicationId=<YOUR_APPLICATION_ID>
            sonar.auth.saml.providerId=https://sts.windows.net/<YOUR_TENANT_ID>/
            sonar.auth.saml.loginUrl=https://login.microsoftonline.com/<YOUR_TENANT_ID>/saml2
            sonar.auth.saml.user.login=http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name
            sonar.auth.saml.user.name=http://schemas.microsoft.com/identity/claims/displayname
            sonar.auth.saml.user.email=http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress
            sonar.auth.saml.group.name=http://schemas.microsoft.com/ws/2008/06/identity/claims/groups
        