apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-dev-secret-syst-2374-sonarqube-admin
  namespace: ns-nb-clone-sonarqube
spec:
  vaultAuthRef: "vault-secrets-operator/vault-dev-kubernetes-syst-2374-sonarqube-auth"
  namespace: "sandbox-alpana"
  refreshAfter: "30s"
  hmacSecretData: true
  type: "kv-v2"
  mount: "syst-2374"
  path: "brm/infrastructure/shared/sonarqube"
  syncConfig:
    instantUpdates: false
  rolloutRestartTargets:
    - kind: StatefulSet
      name: "nb-clone-sonarqube"
  destination:
    name: "nb-clone-sonarqube-admin"
    create: true
    overwrite: true
    type: "Opaque"
    transformation:
      excludeRaw: true
      excludes:
        - ".*"
      templates:
        password:
          text: "{{ get .Secrets \"sonarqube_admin_pass\" }}"
        currentPassword:
          text: "{{ get .Secrets \"sonarqube_admin_pass_old\" }}"