apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-dev-secret-syst-2374-sonarqube-iap
  namespace: ns-nb-clone-sonarqube
spec:
  vaultAuthRef: "vault-secrets-operator/vault-dev-kubernetes-syst-2374-sonarqube-auth"
  namespace: "sandbox-alpana"
  refreshAfter: "30s"
  hmacSecretData: true
  type: "kv-v2"
  mount: "syst-2374"
  path: "brm/infrastructure/shared/sonarqube"
  syncConfig:
    instantUpdates: false
  destination:
    name: "nb-clone-sonarqube-iap"
    create: true
    overwrite: true
    type: "Opaque"
    transformation:
      excludeRaw: true
      excludes:
        - ".*"
      templates:
        key:
          text: "{{ get .Secrets \"sonarqube_oauth2_client_secret\" }}"