apiVersion: v1
kind: Service
metadata:
  labels:
    app: sonarqube
    app.kubernetes.io/managed-by: Helm
    chart: sonarqube-2025.4.2
    heritage: Helm
    release: nb-clone
  name: nb-clone-sonarqube-protected
  namespace: ns-nb-clone-sonarqube
spec:
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: http
  selector:
    app: sonarqube
    release: nb-clone
  sessionAffinity: None
  type: ClusterIP