apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-dev-secret-syst-2374-jenkins-tls
  namespace: default
spec:
  vaultAuthRef: "vault-secrets-operator/vault-dev-syst-2374-approle-auth"
  #vaultAuthRef: "vault-secrets-operator/vault-dev-syst-2374-kubernetes-auth"
  namespace: "sandbox-alpana"
  refreshAfter: "30s"
  hmacSecretData: true
  type: "kv-v2"
  mount: "syst-2374"
  path: "brm/infrastructure/shared/tls-certificates/jenkins.brm.gcp.skycdp.de"
  syncConfig:
    instantUpdates: false
  destination:
    name: "nb-clone-jenkins-tls"
    create: true
    overwrite: true
    type: "kubernetes.io/tls"
    transformation:
      excludeRaw: true
      excludes:
        - ".*"
      templates:
        tls.crt:
          text: "{{ get .Secrets \"jenkins.brm.gcp.skycdp.de_chain_crt\" }}"
        tls.key:
          text: "{{ get .Secrets \"jenkins.brm.gcp.skycdp.de_key\" }}"