apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-dev-secret-syst-2374-sonarqube-tls
  namespace: default
spec:
  vaultAuthRef: "vault-secrets-operator/vault-dev-kubernetes-syst-2374-default-auth"
  namespace: "sandbox-alpana"
  refreshAfter: "30s"
  hmacSecretData: true
  type: "kv-v2"
  mount: "syst-2374"
  path: "brm/infrastructure/shared/tls-certificates/sonarqube.brm.gcp.internal.skycdp.de"
  syncConfig:
    instantUpdates: false
  destination:
    name: "nb-clone-sonarqube-tls"
    create: true
    overwrite: true
    type: "kubernetes.io/tls"
    transformation:
      excludeRaw: true
      excludes:
        - ".*"
      templates:
        tls.crt:
          text: |
            {{- if get .Secrets "sonarqube.brm.gcp.skycdp.de_chain_crt" -}}
            {{ get .Secrets "sonarqube.brm.gcp.skycdp.de_chain_crt" }}
            {{- else -}}
            {{ get .Secrets "sonarqube.brm.gcp.internal.skycdp.de_chain_crt" }}
            {{- end -}}
        tls.key:
          text: |
            {{- if get .Secrets "sonarqube.brm.gcp.skycdp.de_key" -}}
            {{ get .Secrets "sonarqube.brm.gcp.skycdp.de_key" }}
            {{- else -}}
            {{ get .Secrets "sonarqube.brm.gcp.internal.skycdp.de_key" }}
            {{- end -}}
