apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-dev-secret-syst-2374-jenkins-iap
  namespace: ns-nb-clone-jenkins
spec:
  vaultAuthRef: "vault-secrets-operator/vault-dev-kubernetes-syst-2374-jenkins-auth"
  namespace: "sandbox-alpana"
  refreshAfter: "30s"
  hmacSecretData: true
  type: "kv-v2"
  mount: "syst-2374"
  path: "brm/infrastructure/shared/jenkins"
  syncConfig:
    instantUpdates: false
  destination:
    name: "nb-clone-jenkins-iap"
    create: true
    overwrite: true
    type: "Opaque"
    transformation:
      excludeRaw: true
      excludes:
        - ".*"
      templates:
        key:
          text: "{{ get .Secrets \"OAuth_Client_Secret\" }}"